DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	ID			VARCHAR2(20)	PRIMARY KEY,
	PW			VARCHAR2(20)	NOT NULL,
	NAME		VARCHAR2(20)	NOT NULL,
	EMAIL		VARCHAR2(30)	NOT NULL,
	ZONECODE	VARCHAR2(10)	NOT NULL,
	ADDRESS		VARCHAR2(100)	NOT NULL,
	ADDRESSETC	VARCHAR2(100)	NOT NULL,
	PHONE		VARCHAR2(13)	NOT NULL,
	GRADE		NUMBER(3)		NOT NULL,
	REGDATE		DATE			NOT NULL,
	DROPOUT		VARCHAR2(2)		NOT NULL
);
--GRADE: 1 회원 / 2 농부 / 3 관리자

SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES(
'user', '1234', '홍길동', 'hong@hong.com', 
'11176', '서울시 강남구 역삼동', 'KH정보교육원',
'010-1111-2222', 1,SYSDATE, 'N'
);

--회원이 농부 신청서 양식을 작성하면 양식을 확인해서 관리자가 승인해준다.
--이때 승인이란, 해당 아이디를 받아서 데이터베이스에 튜플(레코드)를 만드는 것이다. 

CREATE TABLE FARMER (
	FARMER_KEY		NUMBER(10)		PRIMARY KEY,
	ID				VARCHAR2(20)	NOT NULL,
	FARMER_STATUS	NUMBER(3)		NOT NULL, 
	FARMER_REGDATE	DATE			NOT NULL
);
--FARMER_STATUS : 1 승인대기 / 2 승인완료



