DROP TABLE BILL;
DROP TABLE ORDERINFO;

CREATE TABLE "BILL" 
   (	"ORDER_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"STOCK_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"MEM_ID" VARCHAR2(30)
   );
	 CONSTRAINT "ORDER_PK_ORDER_NO" PRIMARY KEY ("ORDER_NO")
	 CONSTRAINT "ORDER_FK_STOCK_NO" FOREIGN KEY ("STOCK_NO")
	  REFERENCES "BIGSEMI04"."STOCK" ("STOCK_NO") ENABLE, 
	 CONSTRAINT "ORDER_FK_MEM_ID" FOREIGN KEY ("MEM_ID"),
	  REFERENCES "BIGSEMI04"."MEMBER" ("MEM_ID") ENABLE
  
  CREATE TABLE "ORDERINFO" 
   (	"ORDERINFO_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"ORDER_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"ORDERINFO_KG" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDERINFO_STATUS" NUMBER(3,0) NOT NULL ENABLE, 
	"ORDERINFO_DATE" DATE NOT NULL ENABLE, 
	"ORDERINFO_KIND" NUMBER(3,0) NOT NULL ENABLE
   );
	 CONSTRAINT "ORDERINFO_PK_ORDERINFO_NO" PRIMARY KEY ("ORDERINFO_NO")
	 CONSTRAINT "ORDERINFO_FK_ORDER_NO" FOREIGN KEY ("ORDER_NO")
	  REFERENCES "BIGSEMI04"."BILL" ("ORDER_NO") ENABLE
	  
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(1,1,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(2,2,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(3,3,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(4,4,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(5,5,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(6,6,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(7,7,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(8,8,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(9,9,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(10,10,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(11,11,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(12,12,'GUEST');
INSERT INTO BILL (ORDER_NO,STOCK_NO,MEM_ID) VALUES 
(13,13,'GUEST');
	  
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES 
(1,1,2000,1,TIMESTAMP '2020-02-17 08:10:17.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(2,2,2000,1,TIMESTAMP '2020-02-17 08:14:55.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(3,3,2000,1,TIMESTAMP '2020-02-17 08:40:53.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(4,4,2000,2,TIMESTAMP '2020-02-17 11:21:50.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(5,5,2000,2,TIMESTAMP '2020-02-17 11:38:22.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(6,6,0,3,TIMESTAMP '2020-02-19 11:42:45.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(7,7,2000,1,TIMESTAMP '2020-02-16 17:49:55.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(8,8,2000,1,TIMESTAMP '2020-02-16 18:09:57.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(9,9,2000,1,TIMESTAMP '2020-02-16 18:11:41.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(10,10,2000,1,TIMESTAMP '2020-02-17 08:14:32.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(11,11,2000,1,TIMESTAMP '2020-02-17 08:14:32.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(12,12,2000,1,TIMESTAMP '2020-02-17 08:14:32.000000',1);
INSERT INTO ORDERINFO (ORDERINFO_NO,ORDER_NO,ORDERINFO_KG,ORDERINFO_STATUS,ORDERINFO_DATE,ORDERINFO_KIND) VALUES
(13,13,2000,1,TIMESTAMP '2020-02-17 08:14:32.000000',1);


SELECT * 
FROM STOCK S INNER JOIN BILL B ON S.STOCK_NO = B.STOCK_NO
LEFT JOIN ORDERINFO O ON B.ORDER_NO = O.ORDER_NO

SELECT R.RNUM, R.MEM_ID, R.STOCK_NAME, R.AUC_STARTPRICE, R.AUC_REGDATE, R.AUC_ENDDATE, R.AUC_STATUS, R.AUC_NO
FROM (SELECT ROWNUM AS RNUM, A.*, B.*
	FROM AUCTION A, STOCK B
	WHERE A.STOCK_NO = B.STOCK_NO
	ORDER BY A.AUC_REGDATE DESC) R 
WHERE R.RNUM BETWEEN #{from} AND #{to}

SELECT BB.*
FROM	(
		SELECT 	ROWNUM AS RNUM, AA.*	
		FROM	(
				SELECT * 
				FROM STOCK S INNER JOIN BILL B ON S.STOCK_NO = B.STOCK_NO
				LEFT JOIN ORDERINFO O ON B.ORDER_NO = O.ORDER_NO
				ORDER BY O.ORDER_NO DESC
				) AA
		) BB		
WHERE BB.RNUM BETWEEN 1 AND 10